# Warning levels
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  # Basic warnings
  if (CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    add_compile_options(-Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion)
    if (AERONET_WARNINGS_AS_ERRORS)
        add_compile_options(-Werror)
    endif()
  endif()
else()
  if (CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    add_compile_options(-Wall -Wdisabled-optimization)
  endif()
endif()

# Address/UB sanitizers (activated via AERONET_ENABLE_ASAN)
if(AERONET_ENABLE_ASAN)
  if (NOT AERONET_ASAN_OPTIONS)
    set(AERONET_ASAN_OPTIONS -fsanitize=address -fsanitize=undefined -fsanitize=float-divide-by-zero -fno-sanitize-recover)
  endif()
  add_compile_options(${AERONET_ASAN_OPTIONS})
  add_link_options(${AERONET_ASAN_OPTIONS})
  message(STATUS "Activate asan with options ${AERONET_ASAN_OPTIONS}")
endif()

# Clang-Tidy integration
if(AERONET_ENABLE_CLANG_TIDY)
  find_program(CLANG_TIDY "clang-tidy")
  if(CLANG_TIDY)
    message(STATUS "Activate clang-tidy")
  else()
    message(FATAL_ERROR "clang-tidy executable cannot be found")
  endif()
endif()