name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '23 4 * * 1'

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.6
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: 43.84.2
        env:
          LOG_LEVEL: info
          RENOVATE_ALLOWED_COMMANDS: '["node scripts/update_fetchcontent_hashes.mjs --file cmake/Dependencies.cmake"]'
